version: "2"
services:
  app:
    build: ./app
    container_name: "Flask_New"
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: "MySQL_New"
    ports:
      - "3200:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro


